version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: optifit
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: optifit
    volumes:
      - user_service_source:/usr/src/app
      - user_service_node_modules:/usr/src/app/node_modules
    command: npm run start:dev

  # TimescaleDB for logging-service
  timescaledb:
    image: timescale/timescaledb:latest-pg13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: logging_service
    ports:
      - "5433:5432"  # Using 5433 to avoid conflict with existing Postgres
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  logging-service:
    build:
      context: ./services/logging-service
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      timescaledb:
        condition: service_healthy
    environment:
      - PORT=3001
      - NODE_ENV=development
      - DB_HOST=timescaledb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_NAME=logging_service
      - DB_SYNC=true
      - DB_LOGGING=false
      - JWT_SECRET=your_jwt_secret
      - JWT_EXPIRATION=1h
      - EDAMAM_APP_ID=your_app_id
      - EDAMAM_APP_KEY=your_app_key
    volumes:
      - ./services/logging-service:/usr/src/app
      - logging_service_node_modules:/usr/src/app/node_modules
    command: npm run start:dev

  # Uncomment and configure this service as needed:
  #  ai-service:
  #    build:
  #      context: ./services/ai-service
  #      dockerfile: Dockerfile
  #    ports:
  #      - "3002:3000"
  #    depends_on:
  #      - db

volumes:
  pgdata:
  user_service_source:
  user_service_node_modules:
  timescaledb_data:
  logging_service_node_modules:
